dist: xenial

language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

git:
  depth: 1

before_script:
  - go get github.com/Necroforger/dgrouter/exrouter
  - go get github.com/bwmarrin/discordgo
  - go get github.com/mattn/go-sqlite3

script:
  - go build